---
title: "grabFrames"
author: "Naiti Bhatt"
date: "3/9/2021"
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=3, fig.height=3, fig.crop = F,
                      fig.pos = "tb", fig.path='figs/',
                      echo=F, warning=F, cache=F,
                      message=F, sanitize = T)
```

```{r setup, echo=FALSE}
library(tidyverse)
library(here)
library(ggthemes)
library(viridis)
library(egg)
library(igraph)
```

```{r load-data, echo=FALSE}
load(file = here::here('data/preprocessed_data/merged_annotations.RData'))
```
## R Markdown

```{r basic-level-data}
d_basic <- d %>%
  filter(!is.na(basic_level)) %>%
  mutate(age_group = cut(age_day_bin, c(5,12,18,34), labels = c('6-12m','12-18m','18-32m'))) %>%
  filter(!basic_level %in% c('no child hands','allocentric','no object','unknown object','no objects','no child')) %>%
  distinct(public_url, basic_level, child_id, age_days, age_day_bin, age_group) %>%
  ungroup() 
# to check relative to age distribution in larger set
d_age_check <- d %>%
  distinct(public_url, basic_level, child_id, age_days) 
```


```{r basic-level-filtered}
# colllapse across 
d_basic <- d_basic %>%
  mutate(basic_level_all_formats = str_replace(basic_level, '-drawing','')) %>%
  mutate(basic_level_all_formats = str_replace(basic_level_all_formats, '-toy','')) 
d_basic_limited <- d_basic %>%
  filter(!basic_level %in% c('food','toy','book','person')) 
```

```{r basic-level-for-plots}
count_by_category <- d_basic %>%
  mutate(total_images = n()) %>%
  group_by(basic_level)  %>%
  summarize(count = length(public_url), total_images = total_images[1]) %>%
  mutate(Freq = count/total_images) %>%
  ungroup() %>%
  mutate(basic_level = fct_reorder(basic_level, Freq, .desc=TRUE))
```