---
title: "Preprocess visual experience survey data"
author: "Bria Long"
date: "8/27/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(ggthemes)
library(knitr)
library(egg)
library(assertthat)
```
# Load and preprocess data
```{r}
raw_data = read_csv(here('data','vedi_pilot','Visual Experience Development Survey_March 30, 2021_17.49.csv'))

```

```{r}
meta <- read_csv(here::here('data/vedi_pilot/category_metadata.csv')) %>%
  as_tibble()
```

```{r}
aoa <- read_csv(here::here('data/vedi_pilot/VEDI_AoAs.csv')) %>%
  as_tibble() %>%
  select(aoa, definition) %>%
  rename(category = definition)
```

## Loop through question nnames and preproces qualtrics data
```{r}
question_names <- raw_data %>%
  select(contains('_Q')) %>%
  filter(row_number()==1)  

question_type <- question_names %>%
  gather(key = question_id, value = question_text) %>%
  mutate(question_type = case_when(str_detect(question_text,'How often has your child seen') ~ "how_often",
                                   str_detect(question_text,'In what formats has your child seen')  ~ "different_formats", 
                                   str_detect(question_text,'How many different')  ~ "how_many")) %>%
  mutate(category = str_split_fixed(question_text,' -',2)[,1]) %>%
  left_join(meta)

d <- raw_data %>%
  filter(DistributionChannel != 'preview') %>% # not preview
  filter(Finished == 'True') %>%
  filter(Q8 == "Yes") %>% # positive consent
  mutate(childs_age = Q16) %>%
  select(childs_age, ResponseId,contains('_Q')) %>%
  gather(key = question_id, value = response, -childs_age, -ResponseId) %>%
  left_join(question_type, by = c("question_id")) %>%
  select(-category) %>%
  rename(category = category_short)
```

```{r}
assertthat::assert_that(sum(is.na(d$category))==0)
```

## Data structure for how often seen
```{r}
how_often_summary <- d %>%
  filter(question_type == 'how_often') %>%
  filter(!is.na(response)) %>%
  mutate(how_often_numeric= case_when(response == 'Never' ~ 0, 
                                      response == 'Once or twice' ~ 1, 
                                      response == 'A few times' ~ 2, 
                                      response == 'Every few months' ~ 3, 
                                      response == 'Monthly' ~ 4, 
                                      response == 'Weekly' ~ 5, 
                                      response == 'Daily' ~ 6, 
                                      response == 'Multiple times a day' ~ 7
                                      )) %>%
  group_by(category, type) %>%
  dplyr::summarize(how_often_avg = mean(how_often_numeric)) 
```

## Data structure for how many exemplars seen
```{r}
how_many_summary <- d %>%
  filter(question_type == 'how_many') %>%
  filter(!is.na(response)) %>%
  mutate(how_many_numeric= case_when(response == '0' ~ 0, 
                                      response == '1' ~ 1, 
                                      response == '2' ~ 2, 
                                      response == '<5' ~ 3, 
                                      response == '<10' ~ 7.5, 
                                      response == '<25' ~ 17.5, 
                                      response == '25 or more' ~ 40
                                      )) %>%
  group_by(category,type) %>%
  dplyr::summarize(how_many_avg = mean(how_many_numeric)) 

```

## Data structure for counting formats
```{r}
formats <- d %>%
  filter(question_type == 'different_formats') %>%
  filter(!is.na(response)) %>%
  mutate(seen_drawing = str_detect(response,'A drawing')) %>%
  mutate(seen_toy = str_detect(response,'A toy')) %>%
  mutate(seen_photo = str_detect(response,'A photo')) %>%
  mutate(seen_video = str_detect(response,'A video')) %>%
  mutate(seen_life = str_detect(response,'In real life')) 

diff_formats_summary <- formats %>%
  group_by(category) %>%
  summarize(seen_toy_avg = mean(seen_toy), seen_drawing_avg = mean(seen_drawing), seen_photo_avg = mean(seen_photo), seen_video_avg = mean(seen_video), seen_real_life_avg = mean(seen_life)) %>%
  ungroup() %>%
  mutate(categories = fct_reorder(category, seen_real_life_avg, .desc=TRUE))
  
format_count <- formats %>%
  group_by(ResponseId, category, type) %>%
  summarize(count_formats = sum(seen_drawing + seen_toy + seen_photo + seen_video + seen_life)) %>%
  group_by(category, type) %>%
  summarize(avg_num_formats = mean(count_formats))
```

# Seen in real life vs. drawings
```{r}
real_life_by_cat <- formats %>%
  group_by(category, type) %>%
  summarize(avg_real_life = mean(seen_life), avg_seen_drawing = mean(seen_drawing)) 

often_by_cat <- how_often_summary %>%
  group_by(category, type) %>%
  summarize(how_often = mean(how_often_avg)) %>%
  left_join(real_life_by_cat)

ggplot(often_by_cat, aes(x=avg_real_life, y=avg_seen_drawing, color=type, label=category)) + 
  geom_jitter(height=.1, alpha=.8) +
  theme_few(base_size=12) +
  ylim(0,1) +
  xlim(0,1) +
  xlab('Avg. seen in real-life') +
  ylab('Avg. seen as drawing') +
  scale_color_discrete(name="") +
  ggrepel::geom_label_repel(segment.colour="grey", segment.alpha =.2) 

  # scale_size_continuous(name='How often seen', range=c(1,8))

```



# Aggregate data structures
```{r}
experience_raw <- how_often_summary %>%
  left_join(format_count) %>% 
  left_join(how_many_summary) %>%
  mutate(category = fct_reorder(category, how_often_avg, .desc=TRUE)) 
  
experience_summary <- experience_raw %>%
  distinct(category,type, avg_num_formats, how_often_avg, how_many_avg) 
```

# Plot for JSMF pilot data
```{r}
# couldn't get axis labels working
# library(grid)
# text_high <- textGrob("Everday", gp=gpar(fontsize=11))
# text_low <- textGrob("Never", gp=gpar(fontsize=11))

ggplot(experience_summary, aes(x=avg_num_formats, y=how_often_avg, color=type, label=category)) + 
  geom_jitter(height=.1, alpha=.7) +
  theme_few() + 
  ylab('Avg. how often seen') +
  ylim(1,8) +
  xlim(1,5) +
  xlab('Avg. number of formats') +
  geom_smooth(span=10, alpha=.2, color='dark grey') +
  ggrepel::geom_label_repel(segment.colour="grey", segment.alpha =.2) +
  # annotation_custom(text_high,xmin=1,xmax=.5,ymin=7,ymax=7) +
  # annotation_custom(text_low,xmin=1,xmax=.5,ymin=1,ymax=1) +
  scale_color_discrete(name='') +
  theme(legend.position = c(.9, .2))
  coord_cartesian(clip = "off")

ggsave('vedi_pilot_plot.png')

```


```{r}
categories_to_show = c('bird','penny','radio','deer','car','book')
ggplot(experience_summary %>% filter(category %in% categories_to_show), aes(x=category, y=how_often_avg, col=how_many_avg, size=avg_num_formats)) + 
  geom_point(height=.1, alpha=.8) +
  theme_few() + 
  theme(axis.text.x = element_text(angle = 90)) +
  ylim(0,7) +
  ylab('How often seen') +
  scale_color_continuous(name = 'How many exemplars') + 
  xlab('') +
  scale_size_continuous(name = 'How many formats', range = range(1,5), breaks = seq(1,5,1)) 
```


```{r}
formats_compiled <- diff_formats_summary  %>%
  group_by(category) %>%
  mutate(toy_or_drawing = sum(seen_toy_avg + seen_drawing_avg)/2, video_or_photo = sum(seen_photo_avg +  seen_video_avg + seen_real_life_avg)/3) %>%
  mutate(diff = toy_or_drawing - video_or_photo) %>%
  arrange((diff))
```

```{r}
ggplot(formats_compiled, aes(x=video_or_photo, y=toy_or_drawing)) +
  geom_jitter(height=.03, width=.03, alpha=.8, size=2) +
  theme_few(base_size=14) + 
  ylim(0,1) +
  xlim(0,1) + 
  theme(axis.text.x = element_text(angle = 90)) +
  ylab('Proportion seen as toy/drawing') +
  xlab('Proportion seen as photo/video/real-life')  +
  geom_abline(intercept=0, slope=1, color='grey', linetype='dashed') +
  theme(aspect.ratio = 1)

```


```{r}
experience_by_aoa <- experience_summary %>%
  left_join(aoa) %>%
  filter(!is.na(aoa))
  
```


```{r}
cor.test(experience_by_aoa$avg_num_formats, experience_by_aoa$aoa)
cor.test(experience_by_aoa$how_often_avg, experience_by_aoa$aoa)
cor.test(experience_by_aoa$how_many_avg, experience_by_aoa$aoa)
```

# GK look here: aggregated plot for NSF
```{r}
library(grid)
base_size_print=10
label_size=3

empty <- textGrob("", gp=gpar(fontsize=base_size_print))
text_low <- textGrob("Never", gp=gpar(fontsize=base_size_print))
text_high <- textGrob("Everyday", gp=gpar(fontsize=base_size_print))

p1 = ggplot(experience_by_aoa, aes(x=how_often_avg, y=aoa, label=category)) +
  geom_jitter(height=.03, width=.03, alpha=.8, size=2) +
  theme_few(base_size=base_size_print) +
  geom_smooth(span=10, alpha=.2, color='dark grey') +
    ggrepel::geom_label_repel(data = experience_by_aoa %>% filter( (aoa>25 & how_often_avg<4) | (aoa<22 & how_often_avg>5.5)),segment.colour="grey", segment.alpha =.2, aes(color=type), size = label_size) +
  ylim(14,30)+
  xlim(1,8) +
  annotation_custom(text_low,xmin=1,xmax=1,ymin=11,ymax=11) +
  annotation_custom(text_high,xmin=7.5,xmax=7.5,ymin=11,ymax=11) +
  xlab('How often seen') +
  ylab('Avg. age-of-acquisition') +
  theme(legend.position='none', aspect.ratio=1) +
  coord_cartesian(clip='off')

p2 = ggplot(experience_by_aoa, aes(x=avg_num_formats, y=aoa, label=category)) +
  geom_jitter(height=.03, width=.03, alpha=.8, size=2) +
  theme_few(base_size=base_size_print) +
    geom_smooth(span=10, alpha=.2, color='dark grey') +
  ggrepel::geom_label_repel(data = experience_by_aoa %>% filter( (aoa>25 & avg_num_formats<3) | (aoa<22 & avg_num_formats>3.5)),segment.colour="grey", segment.alpha =.2, aes(color=type), size = label_size) +
  ylim(14,30)+
  xlim(1,5) +
  xlab('Number of formats seen') +
  ylab('Avg. age-of-acquisition') +      annotation_custom(empty,xmin=8,xmax=8,ymin=11,ymax=11) +
  theme(legend.position ='none', aspect.ratio=1) +
  scale_color_discrete(name="Category type")  +
  coord_cartesian(clip='off')

p3 = ggplot(experience_by_aoa, aes(x=how_many_avg, y=aoa, label=category)) +
  geom_jitter(height=.03, width=.03, alpha=.8, size=2) +
  theme_few(base_size=base_size_print) +
  geom_smooth(span=10, alpha=.2, color='dark grey') +
  ggrepel::geom_label_repel(data = experience_by_aoa %>% filter( (aoa>24 & how_many_avg<15) | (aoa<22 & how_many_avg>20)),segment.colour="grey", segment.alpha =.2, aes(color=type), size = label_size) +
  ylim(14,30) +
  xlab('Number of exemplars seen') +
  ylab('Avg. age of acquisition') +
  ylab('Avg. age-of-acquisition') +           
  annotation_custom(empty,xmin=8,xmax=8,ymin=11,ymax=11) +
  theme(legend.position='none', aspect.ratio=1)  +
  coord_cartesian(clip='off')
```


```{r}

arranged <- ggarrange(p1,p3,p2, nrow=1) 
ggsave(file='vedi_pilot_nsf_figure.pdf', arranged, width=8.5, height=3)



```

```{r}
long_form <- experience_by_aoa %>% 
  pivot_longer(cols = -c(category,type), names_to="measure", values_to="average")


ggplot(experience_by_aoa, aes(x=how_many_avg, y=aoa, label=category)) +
  geom_jitter(height=.03, width=.03, alpha=.8, size=2) +
  theme_few(base_size=14) +
  geom_smooth(span=10, alpha=.2, color='dark grey') +
  ggrepel::geom_label_repel(data = experience_by_aoa %>% filter( (aoa>25 & how_many_avg<10) | (aoa<22 & how_many_avg>20)),segment.colour="grey", segment.alpha =.2, aes(color=type)) +
  ylim(14,30) +
  xlab('Number of exemplars seen') +
  ylab('Avg. age of acquisition')

```
