---
title: "frame_selection"
author: "Bria Long"
date: "3/25/2021"
output: html_document
---



```{r setup, echo=FALSE}
library(tidyverse)
library(here)
library(ggthemes)
library(viridis)
library(egg)
library(igraph)

```

```{r load-data, echo=FALSE}
load(file = here::here('data/preprocessed_data/merged_annotations.RData'))
```

```{r}
frames_to_annotates <- d %>%
  filter(is.na(basic_level)) %>%
  filter(!category %in% c('Nothing','Other')) %>%
  filter(category %in% c('Toy','Book','Utensil-Dish','Food','SmallObj','Vehicle-toy','Animal-toy')) %>%
  group_by(public_url, img_name) %>%
  summarize(count_cat = n()) %>%
  filter(count_cat >1)

```


```{r}
library(magick)
public_urls = unique(frames_to_annotates$public_url)
img_names_short = unique(frames_to_annotates$img_name)

dir.create(here::here("data/images/for_additional_panoptic"),recursive = TRUE)

for (i in 1:length(public_urls)){
    this_image = image_read(public_urls[i])
    image_write(this_image, here::here("data/images/for_additional_panoptic/", img_names_short[i]))
  } 
```